config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs do
    resources :likes
  end
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  belongs_to :owner, optional: true
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, :images => [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_dog
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @dog.likes.create(user_id: current_user.id)
    end
    redirect_to dog_path(@dog)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to dog_path(@dog)
  end

  private

  def find_dog
    @dog = Dog.find(params[:dog_id])
  end

  def find_like
    @like = @dog.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, dog_id: params[:dog_id]).exists?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.file_field :image, :multiple => true, as: :file %>

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

app/views/dogs/_grid.html.erb
<div class='grid'>
  <%= render partial: 'thumbnail', collection: @dogs, as: :dog %>
  <%= will_paginate @dogs %>
</div>

app/views/dogs/_thumbnail.html.erb
<a href="<%= url_for(dog) %>", data-turbolinks="false", class="text-decoration-none text-reset">
  <div class="card shadow p-3 mb-5 bg-body rounded">
    <h5 class="dog-name card-header"><%= dog.name %></h5>
    <div class="card-body" style="padding: 0">
      <article class="dog">
        <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
      </article>
    </div>
    <p><%= dog.likes.count %> <%= (dog.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  </div>
</a>

app/views/dogs/edit.html.erb
<div class="d-flex flex-column align-items-center justify-content-start">
  <h1>Edit Your Dog</h1>
  <%= render partial: 'form' %>
</div>

app/views/dogs/index.html.erb
<div class="bg-info">
  <%= render partial: "grid" %>
</div>

app/views/dogs/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-start">
  <h1>Add Your Dog</h1>
  <%= render partial: 'form' %>
</div>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>
  <% if @dog.images.count > 1 %>
    <!-- Slider main container -->
    <div class="swiper">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">
        <!-- Slides -->
        <% @dog.images.each do |image| %>
          <div class="swiper-slide">
            <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
          </div>
        <% end %>
      </div>
      <!-- If we need pagination -->
      <div class="swiper-pagination"></div>
      <!-- If we need navigation buttons -->
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    </div>
    <%= javascript_include_tag "carousel" %>
  <% else %>
    <% @dog.images.each do |image| %>
      <div class="swiper-slide">
        <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
      </div>
    <% end %>
  <% end %>

  <% pre_like = @dog.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', dog_like_path(@dog, pre_like), method: :delete %>
  <% else %>
    <%= button_to 'Like', dog_likes_path(@dog), method: :post %>
  <% end %>

  <p><%= @dog.likes.count %> <%= (@dog.likes.count) == 1 ? 'Like' : 'Likes'%></p>

  <p><%= @dog.description %></p>

  <div class="btn-group m-2" role="group" aria-label="Edit dog and delete dog button group">
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path, class: "btn btn-primary text-decoration-none link-light" %>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, class: "btn btn-primary text-decoration-none link-light", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
    />
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header class="bg-warning text-white bg-opacity-75 p-3">
        <h1><%= link_to "Dog Profile Demo", root_path, class: "text-decoration-none text-reset bg-info p-2 rounded" %></h1>
        <div class="actions">
          <% if current_user %>
            <div class="btn-group" role="group" aria-label="Add Dog, Sign Out">
              <%= link_to "Add your dog", new_dog_path, class: "btn btn-primary text-decoration-none link-light" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary text-decoration-none link-light" %>
            </div>
          <% else %>
            <div class="btn-group m-2" role="group" aria-label="Sign In, Sign Up">  
              <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary text-decoration-none link-light" %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary text-decoration-none link-light" %>
            </div>
          <% end %>
        </div>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>
  </body>
</html>